### ISSUE TITLE
problem with gulp prepublish

### ISSUE THREAD

**Issue by adamaltman** [Rebilly/generator-openapi-repo#5] opened 2016-10-05 18:56 UTC
```
$ npm install -g generator-openapi-repo

> generator-openapi-repo@0.6.0 prepublish /home/adam/Projects/generator-openapi-repo
> gulp prepublish

sh: 1: gulp: not found

npm ERR! addLocal Could not install /home/adam/Projects/generator-openapi-repo
npm ERR! Linux 4.2.0-42-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "generator-openapi-repo"
npm ERR! node v4.0.0
npm ERR! npm  v3.10.8
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! generator-openapi-repo@0.6.0 prepublish: `gulp prepublish`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the generator-openapi-repo@0.6.0 prepublish script 'gulp prepublish'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the generator-openapi-repo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp prepublish
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs generator-openapi-repo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls generator-openapi-repo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/adam/Projects/npm-debug.log
```

**Comment by adamaltman** [comment] 2016-10-05 18:59
I tried upgrading node, and still no luck.  I assume I need to install gulp.  But I think this repo should be fixed to note that dependency.

```
$ npm install -g generator-openapi-repo

> generator-openapi-repo@0.6.0 prepublish /home/adam/Projects/generator-openapi-repo
> gulp prepublish

sh: 1: gulp: not found

npm ERR! addLocal Could not install /home/adam/Projects/generator-openapi-repo
npm ERR! Linux 4.2.0-42-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "generator-openapi-repo"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! generator-openapi-repo@0.6.0 prepublish: `gulp prepublish`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the generator-openapi-repo@0.6.0 prepublish script 'gulp prepublish'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the generator-openapi-repo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp prepublish
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs generator-openapi-repo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls generator-openapi-repo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/adam/Projects/npm-debug.log
```

**Comment by IvanGoncharov** [comment] 2016-10-12 16:35
@adamaltman I can reproduce this issue only if I run `npm install -g generator-openapi-repo` in a folder which has this repo cloned in it. Do you have the same setup?
If so than it not a bug since you try to build & install local repo.

**Comment by adamaltman** [comment] 2016-10-12 16:49
ahh ok.

**Comment by IvanGoncharov** [comment] 2016-10-12 16:53
@adamaltman NPM first checks for a local folder with this name and only then for package at the registry.

**Comment by IvanGoncharov** [comment] 2016-10-12 17:24
@adamaltman If you run `npm install` inside `generator-openapi-repo` it should fix this issue.

**Comment by IvanGoncharov** [comment] 2016-10-21 21:31
@adamaltman Can I close this issue?

**Comment by RomanGotsiy** [comment] 2017-08-17 07:51
closing for inactivity

**Closed by RomanGotsiy** 2017-08-17 07:51 UTC
Labels: bug
